# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    accard.controller.configuration_factory.class: DAG\Bundle\ResourceBundle\Controller\ConfigurationFactory
    accard.controller.parameters_parser.class: DAG\Bundle\ResourceBundle\Controller\ParametersParser
    accard.expression_language.class: DAG\Bundle\ResourceBundle\ExpressionLanguage\ExpressionLanguage
    accard.form.type.object_to_identifier.class: DAG\Bundle\ResourceBundle\Form\Type\ObjectToIdentifierType
    accard.event_subscriber.load_orm_metadata.class: DAG\Bundle\ResourceBundle\EventListener\LoadORMMetadataSubscriber
    accard.event_subscriber.kernel_controller.class: DAG\Bundle\ResourceBundle\EventListener\KernelControllerSubscriber
    accard.import.resource_factory.class: DAG\Bundle\ResourceBundle\Import\ResourceResolvingFactory
    accard.import.manager_registry.class: DAG\Bundle\ResourceBundle\Import\ManagerRegistry
    accard.import.registry.class: DAG\Bundle\ResourceBundle\Import\Registry
    accard.import.record_resolver.class: DAG\Bundle\ResourceBundle\Import\RecordResolver
    accard.import.initializer.class: DAG\Bundle\ResourceBundle\Import\Initializer
    accard.import.converter.class: DAG\Bundle\ResourceBundle\Import\Converter
    accard.import.persister.class: DAG\Bundle\ResourceBundle\Import\Persister
    accard.import.runner.class: DAG\Bundle\ResourceBundle\Import\Runner
    accard.import.event_subscriber.class: DAG\Bundle\ResourceBundle\EventListener\ImporterEventSubscriber
    jms_serializer.identifier_handler.class: DAG\Bundle\ResourceBundle\Serializer\IdentifierHandler
    jms_serializer.property_handler.class: DAG\Bundle\ResourceBundle\Serializer\PropertyHandler
    accard.expression_language.extension.resource.class: DAG\Bundle\ResourceBundle\ExpressionLanguage\ResourceExtension

services:
    accard.expression_language.extension.resource:
        class: %accard.expression_language.extension.resource.class%
        tags: [{ name: accard.expression_language_extension }]

    accard.controller.configuration_factory:
        class: %accard.controller.configuration_factory.class%
        arguments: ["@accard.controller.parameters_parser"]

    accard.controller.parameters_parser:
        class: %accard.controller.parameters_parser.class%
        arguments: ["@accard.expression_language"]

    accard.expression_language:
        class: %accard.expression_language.class%
        calls: [["setContainer", ["@service_container"]]]

    accard.event_subscriber.load_orm_metadata:
        class: %accard.event_subscriber.load_orm_metadata.class%
        arguments: ["%accard.config.classes%", "%accard.config.inheritance%"]
        tags: [{ name: doctrine.event_subscriber }]

    accard.event_subscriber.kernel_controller:
        class: %accard.event_subscriber.kernel_controller.class%
        arguments: ["@security.authorization_checker", "@accard.expression_language"]
        tags: [{ name: kernel.event_subscriber }]

    accard.form.type.object_to_identifier:
        class: %accard.form.type.object_to_identifier.class%
        abstract: true

    accard.import.registry:
        class: %accard.import.registry.class%
        calls: [["setContainer", ["@service_container"]]]

    accard.import.manager_registry:
        class: %accard.import.manager_registry.class%
        calls: [["setContainer", ["@service_container"]]]

    accard.import.resource_factory:
        class: %accard.import.resource_factory.class%
        calls: [["setContainer", ["@service_container"]]]

    accard.import.record_resolver:
        class: %accard.import.record_resolver.class%
        arguments:
            - @accard.import.resource_factory

    accard.import.runner:
        class: %accard.import.runner.class%
        arguments:
            - @accard.import.resource_factory
            - @accard.import.registry

    accard.import.initializer.default:
        class: %accard.import.initializer.class%

    accard.import.persister.default:
        class: %accard.import.persister.class%

    accard.import.converter.default:
        class: %accard.import.converter.class%

    accard.import.event.post_import:
        class: %accard.import.event_subscriber.class%
        tags: [{ name: kernel.event_subscriber }]

    jms_serializer.identifier_handler:
        class: %jms_serializer.identifier_handler.class%
        tags: [{ name: jms_serializer.subscribing_handler }]

    jms_serializer.property_handler:
        class: %jms_serializer.property_handler.class%
        tags: [{ name: jms_serializer.subscribing_handler }]

#    accard.importer.static:
#        class: DAG\Bundle\ResourceBundle\Import\StaticImporter
#        tags:
#            - { name: accard.importer, importer: static }
