# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.twig.extension.resource.class: DAG\Bundle\ResourceBundle\Twig\ResourceExtension
    accard.twig.extension.resource.pagination_template: 'AccardResourceBundle:Twig:paginate.html.twig'
    accard.twig.extension.resource.sorting_template: 'AccardResourceBundle:Twig:sorting.html.twig'

services:

    accard.twig.extension.resource:
        class: %accard.twig.extension.resource.class%
        arguments:
            - @router
            - %accard.import.signals%
            - %accard.twig.extension.resource.pagination_template%
            - %accard.twig.extension.resource.sorting_template%
        tags:
            - { name: twig.extension }
            - { name: kernel.event_listener, event: kernel.request, method: fetchRequest }
