# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.event_subscriber.field.load_orm_metadata.class: DAG\Bundle\FieldBundle\EventListener\LoadORMMetadataSubscriber

services:

    accard.event_subscriber.field.load_orm_metadata:
        class: %accard.event_subscriber.field.load_orm_metadata.class%
        arguments: ["%accard.field.subjects%"]
        tags:
            - { name: doctrine.event_subscriber }
