# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Field\Model\Field:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: "name", message: accard.field.name.unique, groups: ['accard'] }
    properties:
        name:
            - NotBlank: { message: accard.field.name.not_blank, groups: ['accard'] }
            - Regex: { pattern: "/^[a-z0-9-]+$/", message: accard.field.name.slug, groups: ['accard'] }
            - Length: { min: 3, max: 120, minMessage: accard.field.name.length.min, maxMessage: accard.field.name.length.max, groups: ['accard'] }
        presentation:
            - NotBlank: { message: accard.field.presentation.not_blank, groups: ['accard'] }
            - Length: { min: 3, max: 120, minMessage: accard.field.presentation.length.min, maxMessage: accard.field.presentation.length.max, groups: ['accard'] }
        type:
            - NotBlank: { message: accard.field.type.not_blank, groups: ['accard'] }
            - Choice: { callback: ['DAG\Component\Field\Model\FieldTypes', 'getKeys'], strict: true, message: accard.field.type.choice, groups: ['accard'] }
        option:
            - Type: { type: DAG\Component\Option\Model\OptionInterface, message: accard.field.option.type, groups: ['accard'] }
        allowMultiple:
            - Type: { type: bool, message: accard.field.option.type, groups: ['accard'] }

DAG\Component\Field\Model\FieldValue: 
    properties:
        subject:
            - NotBlank: { message: accard.field_value.subject.not_blank, groups: ['accard'] }
            - Type: { type: DAG\Component\Field\Model\FieldSubjectInterface, message: accard.field_value.subject.type, groups: ['accard'] }
        field:
            - NotBlank: { message: accard.field_value.field.not_blank, groups: ['accard'] }
            - Type: { type: DAG\Component\Field\Model\FieldInterface, message: accard.field_value.field.type, groups: ['accard'] }
