# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.templating.helper.settings.class: DAG\Bundle\SettingsBundle\Templating\Helper\SettingsHelper

services:

    accard.templating.helper.settings:
        class: %accard.templating.helper.settings.class%
        arguments: ['@accard.settings.manager']
        tags:
            - { name: templating.helper, alias: accard_settings }