# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Bundle\SettingsBundle\Model\Parameter:
    properties:
        namespace:
            - NotBlank:
                message: accard.settings.parameter.namespace.not_blank
            - Length:
                min: 1
                minMessage: accard.settings.parameter.namespace.min_length
                max: 120
                maxMessage: accard.settings.parameter.namespace.max_length
        name:
            - NotBlank:
                message: accard.settings.parameter.name.not_blank
            - Length:
                min: 1
                minMessage: accard.settings.parameter.name.min_length
                max: 120
                maxMessage: accard.settings.parameter.name.max_length
