# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.event_subscriber.prototype.load_orm_metadata.class: DAG\Bundle\PrototypeBundle\EventListener\LoadORMMetadataSubscriber
    accard.repository.prototype.class: DAG\Bundle\PrototypeBundle\Doctrine\ORM\PrototypeRepository
    accard.twig.extension.prototype.class: DAG\Bundle\PrototypeBundle\Twig\PrototypeExtension

services:

    accard.event_subscriber.prototype.load_orm_metadata:
        class: %accard.event_subscriber.prototype.load_orm_metadata.class%
        arguments: ["%accard.prototype.subjects%"]
        tags:
            - { name: doctrine.event_subscriber }

    accard.repository.prototype:
        class: %accard.repository.prototype.class%
        factory_service: doctrine
        factory_method: getRepository
        arguments:
             - DAG\Component\Prototype\Model\Prototype

    accard.twig.extension.prototype:
        class: %accard.twig.extension.prototype.class%
        calls:
            - ["setContainer", ["@service_container"]]
        tags: [{ name: twig.extension }]