# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Resource\Model\Import:
    type: mappedSuperclass
    table: accard_import
    repositoryClass: DAG\Bundle\ResourceBundle\Doctrine\ORM\ImportRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        active:
            type: boolean
            nullable: false
        startTimestamp:
            type: decimal
            scale: 3
            precision: 13
            nullable: false
        endTimestamp:
            type: decimal
            scale: 3
            precision: 13
            nullable: false
        importer:
            type: string
            length: 36
            nullable: false
        criteria:
            type: array
            nullable: false