# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Resource\Model\Log:
    type: mappedSuperclass
    table: accard_log
    repositoryClass: DAG\Bundle\ResourceBundle\Doctrine\ORM\LogRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        user:
            targetEntity: DAG\Component\Resource\Model\UserInterface
            joinColumn:
                name: userId
                referencedColumnName: id
                nullable: false

    fields:
        logDate:
            type: datetime
            nullable: false
        action:
            type: string
            length: 16
            nullable: false
        resource:
            column: resourceName
            type: string
            length: 32
            nullable: false
        resourceId:
            type: integer
            nullable: true
        route:
            type: string
            length: 100
            nullable: false
        attributes:
            column: uriAttributes
            type: json_array
            nullable: true
        query:
            column: uriQuery
            type: json_array
            nullable: true
        request:
            column: uriRequest
            type: json_array
            nullable: true