DAG\Bundle\SettingsBundle\Model\Parameter:
    type: mappedSuperclass
    table: accard_setting

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        namespace:
            type: string
            length: 120
            nullable: false
        name:
            type: string
            length: 120
            nullable: false
        value:
            type: object
            nullable: true
