# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Prototype\Model\Prototype:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 120
            nullable: false
        presentation:
            type: string
            length: 120
            nullable: false
        description:
            type: string
            length: 255
            nullable: true
