# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.provider.option.class: DAG\Bundle\OptionBundle\Provider\OptionProvider
    accard.form.type.option_choice.class: DAG\Bundle\OptionBundle\Form\Type\OptionChoiceType
    accard.form.type.option_order_choice.class: DAG\Bundle\OptionBundle\Form\Type\OptionOrderChoiceType

services:

    accard.provider.option:
        class: %accard.provider.option.class%
        arguments:
            - @accard.repository.option

    accard.form.type.option:
        class: %accard.form.type.option.class%
        arguments:
            - %accard.model.option.class%
            - %accard.validation_group.option%
        tags:
            - { name: form.type, alias: accard_option }

    accard.form.type.option_value:
        class: %accard.form.type.option_value.class%
        arguments:
            - %accard.model.option_value.class%
            - %accard.validation_group.option_value%
        tags:
            - { name: form.type, alias: accard_option_value }

    accard.form.type.option_choice:
        class: %accard.form.type.option_choice.class%
        arguments:
            - %accard.model.option.class%
        tags:
            - { name: form.type, alias: accard_option_choice }

    accard.form.type.option_order_choice:
        class: %accard.form.type.option_order_choice.class%
        tags:
            - { name: form.type, alias: accard_option_order_choice }