# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.templating.helper.option.class: DAG\Bundle\OptionBundle\Templating\Helper\OptionHelper

services:

    accard.templating.helper.option:
        class: %accard.templating.helper.option.class%
        arguments: ['@accard.provider.option']
        tags:
            - { name: templating.helper, alias: accard_option }