# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Option\Model\Option: 
    properties: {}

DAG\Component\Option\Model\OptionValue:
    properties:
        value:
            - NotBlank: { message: accard.option.not_blank, groups: ['accard']}
